= netzteil-http(7)
:doctype:    manpage
:man source: opennetzteil

== Name

netzteil-http - a programming interface for power supplies over http

== Description

OpenNetzteil provides a uniform HTTP API for powersupplies to be controlled over HTTP.
Usually, these devices can be controlled over a device specific and loosely specified protocol called SCPI.
Such powersupplies are accessed differently, some possibilities are USB, TCP, Serial Line, …
The HTTP API, described in this document, aims to be a proxy which can be used to run even multiple, different power supplies on one machine.
Authentication, authorization, and other security mechanism are not in the scope of this API.
Use a reverse proxy for implementing more sophisticated HTTP techniques.

The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be interpreted as described in BCP 14 [RFC2119] [RFC8174] when, and only when, they appear in all capitals, as shown here.

== API

Every GET endpoint delivers data encoded in JSON (RFC7159).
Every PUT endpoint accepts data encoded in JSON.
If there is only one device available, a reduces API MAY be provided by implementations.
All endpoints MUST be prepended the opennetzteil namespace indicator: `/_netzteil/api/`.
The full path of the `/devices` endpoint looks like the following: `/_netzteil/api/devices`.

GET|PUT (OPTIONAL) `/device`::
    If **only one** device is served, this endpoint points to `/devices/0/…`.
    This endpoint MAY use an HTTP 308 redirect to the appropriate endpoint.
    The API using these endpoints is called reduced API.

GET (REQUIRED) `/devices`::
    Query the available power supplies.

GET (REQUIRED) `/devices/{id}/out`::
    Query the status of the master output.
    Returns a boolean JSON body: `true`, or `false`.

PUT (REQUIRED) `/devices/{id}/out`::
    Set the status of the master output.
    Accepts a boolean JSON body: `true`, or `false`.

GET (REQUIRED) `/devices/{id}/ident`::
    Returns the device indentity.
    Typically, this is the model name, e.g. `RND 320-KD3005P V2.0`.

PUT (OPTIONAL) `/devices/{id}/beep`::
    TODO

GET (OPTIONAL) `/devices/{id}/status`::
    Query status information.
    The returned data is device specific.

GET/PUT (OPTIONAL) `/devices/{id}/channel`::
    If the device has *only one* channel, this endpoint points to `/devices/{id}/channels/0`.
    This endpoint MAY use an HTTP 308 redirect to the appropriate endpoint.
    The API using these endpoints is called reduced API.

GET (REQUIRED) `/devices/{id}/channels`::
    Returns the number of available channels as an integer.

GET (REQUIRED) `/devices/{id}/channels/{channel}/current`::
    TODO

PUT (REQUIRED) `/devices/{id}/channels/{channel}/current`::
    TODO

GET (REQUIRED) `/devices/{id}/channels/{channel}/voltage`::
    TODO

PUT (REQUIRED) `/devices/{id}/channels/{channel}/voltage`::
    `10.45`

GET (OPTIONAL) `/devices/{id}/channels/{channel}/voltage/ws?interval={ms}`::
    TODO

GET (OPTIONAL) `/devices/{id}/channels/{channel}/current/ws?interval={ms}`::
    TODO

GET (OPTIONAL) `/devices/{id}/channels/{channel}/measurements/ws?interval={ms}`::
    TODO

GET (REQUIRED) `/devices/{id}/channels/{channel}/out`::
    TODO

PUT (REQUIRED) `/devices/{id}/channels/{channel}/out`::
    TODO

GET (REQUIRED) `/devices/{id}/channels/{channel}/ocp`::
    TODO

PUT (REQUIRED) `/devices/{id}/channels/{channel}/ocp`::
    TODO

GET (REQUIRED) `/devices/{id}/channels/{channel}/ovp`::
    TODO

PUT (REQUIRED) `/devices/{id}/channels/{channel}/ovp`::
    TODO

== Authors

Maintained by Stefan Tatschner <stefan@rumpelsepp.org>.
The Git repository is hosted here: https://git.sr.ht/~rumpelsepp/opennetzteil
