= netzteil-http(7)
:doctype:    manpage
:man source: opennetzteil

== Name

netzteil-http - a programming interface for power supplies over http

== Description

OpenNetzteil provides a uniform HTTP API for powersupplies to be controlled over HTTP.
Usually, these devices can be controlled over a device specific and loosely specified protocol called SCPI.
Such powersupplies are accessed differently, some possibilities are USB, TCP, Serial Line, …
The HTTP API, described in this document, aims to be a proxy which can be used to run even multiple, different power supplies on one machine.
Authentication, authorization, and other security mechanism are not in the scope of this API.
Use a reverse proxy for implementing more sophisticated HTTP techniques.

The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be interpreted as described in BCP 14 [RFC2119] [RFC8174] when, and only when, they appear in all capitals, as shown here.

== API

This API is also called the complete API.
Every GET endpoint delivers data encoded in JSON (RFC7159).
Every PUT endpoint accepts data encoded in JSON.
If there is only one device available, a reduces API MAY be provided by implementations.
All endpoints MUST be prepended the opennetzteil namespace indicator: `/_netzteil/api/`.
The full endpoint path of the `/devices` endpoint looks like the following: `/_netzteil/api/devices`.

GET /devices::
    Query the available power supplies.

GET /devices/{id}/out::
    TODO

PUT /devices/{id}/out::
    `true`

GET /devices/{id}/ident::
    TODO

PUT /devices/{id}/beep::
    TODO

GET /devices/{id}/channels::
    TODO

GET /devices/{id}/channels/{channel}/current::
    TODO

PUT /devices/{id}/channels/{channel}/current::
    TODO

GET /devices/{id}/channels/{channel}/voltage::
    TODO

PUT /devices/{id}/channels/{channel}/voltage::
    `10.45`

GET /devices/{id}/channels/{channel}/out::

PUT /devices/{id}/channels/{channel}/out::
    TODO

GET /devices/{id}/channels/{channel}/ocp::
    TODO

PUT /devices/{id}/channels/{channel}/ocp::
    TODO

GET /devices/{id}/channels/{channel}/ovp::
    TODO

PUT /devices/{id}/channels/{channel}/ovp::
    TODO

== Reduced API

The reduced API is optional if **only one** device is served via an opennetzteil application.
The reduced API MAY be implemented using an HTTP 308 redirect to the appropriate endpoint of the complete API.
If two or more devices are served, all endpoints of the reduced API MAY return a 404 error.
If no 308 redirects are used, the responses MUST be served directly from the reduced API.
All endpoints MUST be prepended the opennetzteil namespace indicator: `/_netzteil/api/`.

GET /device/out::
    TODO

PUT /device/out::
    `true`

GET /device/ident::
    TODO

PUT /device/beep::
    TODO

GET /device/channels::
    TODO

GET /device/channels/{channel}/current::
    TODO

PUT /device/channels/{channel}/current::
    TODO

GET /device/channels/{channel}/voltage::
    TODO

PUT /device/channels/{channel}/voltage::
    `10.45`

GET /device/channels/{channel}/out::
    TODO

PUT /device/channels/{channel}/out::
    TODO

GET /device/channels/{channel}/ocp::
    TODO

PUT /device/channels/{channel}/ocp::
    TODO

GET /device/channels/{channel}/ovp::
    TODO

PUT /device/channels/{channel}/ovp::
    TODO
